### PR TITLE
fix: render the proper witnesses in each place

### LINKED ISSUE #34: fix: Places sometimes have the wrong witness
For example `Sport club` > `Analyst` is wrong.

### PR DESCRIPTION
**Pull request by fmaclen**
Fixes #34

### CODE REVIEW

File: src/lib/game.ts [hunk 1]
```diff
@@ -439,17 +439,16 @@ function getLocalizedPlaces(LL: TranslationFunctions): LocalizedPlace[] {
...
 
 	for (const placeKey of placeKeys) {
-		const validKey = placeKey as keyof Translation['scenes']['places'];
-		const placeIndex = placeKey as keyof typeof Place;
+		const translationKey = placeKey as keyof Translation['scenes']['places'];
+
 		places.push({
-			place: Place[placeIndex],
-			name: LL.scenes.places[validKey](),
+			place: parseInt(placeKey),
```
Comment (fmaclen) [inline src/lib/game.ts:445]: Passing the key `"0"` as a number `0` fixes the issue.

File: src/lib/game.ts [hunk 2]
```diff
@@ -495,20 +495,24 @@ function getLocalizedWitnesses(LL: TranslationFunctions, place: Place): Localize
...
 			break;
 		case Place.STOCK_EXCHANGE:
-		default:
 			possibleWitnesses = [Witness.ANALYST, Witness.MESSENGER, Witness.TRADER];
+			break;
+		default:
+			possibleWitnesses = [];
 	}
 
+	if (possibleWitnesses.length === 0) throw new Error('No witnesses found for this place.');
```
Comment (fmaclen) [inline src/lib/game.ts:504]: This error is not surfaced to the UI but might help debug this in the future.
